# Generated by Django 5.0.6 on 2024-06-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
