# Generated by Django 5.0.6 on 2024-06-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
