# Generated by Django 5.0.6 on 2024-06-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_auth', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='user_auth_customuser_email_or_phone',
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('email__isnull', True), ('phone__isnull', False)), models.Q(('email__isnull', False), ('phone__isnull', True)), models.Q(('email__isnull', True), ('phone__isnull', True)), _connector='OR'), name='user_auth_customuser_email_or_phone'),
        ),
    ]
